RegistroPiscicola/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pagina.urls')),
    path('',include('registro.urls')),
    path('',include('control.urls')),
    path('',include('inventario.urls')),
    path('',include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

control/urls.py
from django.urls import path
from .views import *

app_name = 'control'

urlpatterns = [
    # ----muestreo
    path('cultivos/<int:cultivo_id>/muestreos/', muestreo_listar, name='muestreo_listar'),
    path('cultivos/<int:cultivo_id>/muestreos/grafica/', grafica_muestreo, name='grafica_muestro'),
    path('cultivos/<int:cultivo_id>/muestreos/registrar/', muestreo_registrar, name='muestreo_registrar'),
    path('cultivos/<int:cultivo_id>/muestreos/<int:muestreo_id>/editar/', muestreo_editar, name='muestreo_editar'),
    path('cultivos/<int:cultivo_id>/muestreos/<int:muestreo_id>/', muestreo_detalle, name='muestreo_detalle'),
    path('cultivos/<int:cultivo_id>/mortalidad/', mortalidad_registrar, name='mortalidad_registrar'),
    # ----alimentacion
    path('cultivos/<int:cultivo_id>/alimentacion/', alimentacion_listar, name='alimentacion_listar'),
    path('cultivos/<int:cultivo_id>/alimentacion/registrar/', alimentacion_registrar, name='alimentacion_registrar'),
    path('cultivos/<int:cultivo_id>/alimentacion/<int:alimentacion_id>/editar/', alimentacion_editar,
         name='alimentacion_editar'),
    # ----calidad agua
    path('estanques/<int:estanque_id>/calidad_agua/', calidad_agua_listar, name='calidad_agua_listar'),
    path('estanques/<int:estanque_id>/calidad_agua/registrar/', calidad_agua_registrar,
         name='calidad_agua_registrar'),
    path('estanques/<int:estanque_id>/calidad_agua/<int:calidad_agua_id>/', calidad_agua_detalle,
         name='calidad_agua_detalle'),
    path('estanques/<int:estanque_id>/calidad_agua/<int:calidad_agua_id>/editar/', calidad_agua_editar,
         name='calidad_agua_editar'),
    path('estanques/<int:estanque_id>/calidad_agua/graficas_agua/', graficas_agua, name='graficas_agua'),
    path('estanques/calidad_agua_rangos/', calidad_agua_rangos_create, name='calidad_agua_rangos_create'),
]

users/urls.py
from django.urls import path
from users import views as user_views
from django.contrib.auth.decorators import login_required

# Python Django Tutorial: Full-Featured Web App Part 7 - Login and Logout System
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('registrar/', user_views.registrar, name='registrar'),
    path('ingresar/', auth_views.LoginView.as_view(template_name='users/ingresar.html'), name='ingresar'),
    path('salir/', auth_views.LogoutView.as_view(template_name='users/salir.html'), name='salir'),
    path('perfil/', user_views.perfil, name='perfil'),
]

control/forms.py
from django import forms
from .models import *
from cuser.middleware import CuserMiddleware


class MortalidadForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MortalidadForm, self).__init__(*args, **kwargs)
        self.fields['fecha_registro'].widget.attrs['readonly'] = True

    class Meta:
        model = Mortalidad
        fields = ['peces_muertos', 'fecha_registro']


class MuestreoForm(forms.ModelForm):
    class Meta:
        model = Muestreo
        fields = ['peso_promedio_gr', 'talla_promedio_cm', 'valor_ajuste_tabla', 'observaciones', 'fecha_registro']


class AlimentacionForm(forms.ModelForm):  # en realidad es racion
    def __init__(self, *args, **kwargs):
        super(AlimentacionForm, self).__init__(*args, **kwargs)
        user = CuserMiddleware.get_user()
        self.fields['tipo_concentrado'] = forms.ModelChoiceField(
            queryset=Concentrado.objects.filter(finca=user.profile.trabaja_en))

    class Meta:
        model = Racion
        fields = ['cantidad_gr', 'tipo_concentrado', 'fecha_registro']


class CalidadAguaForm(forms.ModelForm):
    class Meta:
        model = Calidad_agua
        exclude = ['estanque','responsable', 'fecha_registro', 'fecha_update']


class CalidadAguaRangosForm(forms.ModelForm):  # las clases hazlas con camelCase
    class Meta:
        model = Rangos_calidad_agua
        fields = '__all__'
        exclude = ['finca']

control/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from datetime import datetime
import pytz
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import decimal


@login_required
def muestreo_listar(request, cultivo_id):
    cultivo = get_object_or_404(Cultivo, pk=cultivo_id)
    muestreo_list = Muestreo.objects.filter(cultivo=cultivo_id)
    context = {
        'cultivo': cultivo,
        'muestreo_list': muestreo_list
    }
    return render(request, 'control/muestreo_list.html', context)


@login_required
def muestreo_registrar(request, cultivo_id):
    cultivo = get_object_or_404(Cultivo, pk=cultivo_id)
    form = MuestreoForm()
    if request.method == 'POST':
        form = MuestreoForm(request.POST)
        if form.is_valid():
            peso = form.cleaned_data['peso_promedio_gr']
            muestreo = form.save(commit=False)
            muestreo.cultivo = cultivo
            muestreo.responsable = request.user
            # muestreo.b = muestreo.biomasa()
            # muestreo.a_d = muestreo.ajuste_dieta()
            # muestreo.g_d_p = muestreo.ganancia_diaria_peso()
            # muestreo.f_c_a#  = muestreo.factor_conversion_alimenticia()
            muestreo.save()
            # http://documentacion.ideam.gov.co/openbiblio/bvirtual/001819/Winisis/Pagina/ord_cont10.htm

            if 40 < peso < 120:
                cultivo.etapa = "levante"
                cultivo.save()
            if peso >= 120:
                cultivo.etapa = "engorde"
                cultivo.save()
            return redirect('cultivo_detalle', cultivo_id)

    context = {
        'cultivo': cultivo,
        'form': form
    }
    return render(request, 'control/muestreo_registrar.html', context)


@login_required
def muestreo_detalle(request, cultivo_id, muestreo_id):
    muestreo = get_object_or_404(Muestreo, pk=muestreo_id, cultivo=cultivo_id)
    context = {
        'muestreo': muestreo
    }
    return render(request, 'control/muestreo_detalle.html', context)

@login_required
def muestreo_editar(request, cultivo_id, muestreo_id):
    pass


@login_required
def grafica_muestreo(request, cultivo_id):
    cultivo = get_object_or_404(Cultivo, id=cultivo_id)
    muestreos = Muestreo.objects.filter(cultivo=cultivo)
    fechas = []
    peso = []
    talla = []
    for muestreo in muestreos:
        peso.append(float(muestreo.peso_promedio_gr))
        fechas.append(muestreo.fecha_registro.strftime('%d-%m-%Y'))
        talla.append(float(muestreo.talla_promedio_cm))

    context = {
        "cultivo": cultivo,
        "object_list": muestreos,
        "peso": peso,
        "fechas": fechas,
        "talla": talla,
    }
    return render(request, 'control/grafica_muestreo.html', context)


@login_required
def mortalidad_registrar(request, cultivo_id):
    form = MortalidadForm()
    cultivo = get_object_or_404(Cultivo, pk=cultivo_id)
    if request.method == 'POST':
        form = MortalidadForm(request.POST)
        if form.is_valid():
            mortalidad = form.save(commit=False)
            peces_muertos = form.cleaned_data.get('peces_muertos')
            if peces_muertos == 0:
                messages.info(request, 'no se registró mortalidad.')
                return redirect('cultivo_detalle', cultivo_id)
            mortalidad.cultivo = cultivo
            mortalidad.responsable = request.user
            mortalidad.save()
            return redirect('cultivo_detalle', cultivo_id)
    return render(request, 'control/mortalidad_registrar.html', {'form': form, 'cultivo': cultivo})


# ----alimentación----------------------------------------------------------------------------------------------------------
@login_required
def alimentacion_listar(request, cultivo_id):
    cultivo = get_object_or_404(Cultivo, id=cultivo_id)
    alimentacion_list = Alimentacion.objects.filter(cultivo=cultivo_id)
    for alimentacion in alimentacion_list:
        if alimentacion.racion_set.count() == 0:
            alimentacion.delete()
    alimentacion_list = Alimentacion.objects.filter(cultivo=cultivo_id)
    return render(request, 'control/alimentacion_list.html',
                  {'alimentacion_list': alimentacion_list, 'cultivo': cultivo})


@login_required
def alimentacion_registrar(request, cultivo_id):  # ración
    hoy = datetime.today().date()
    cultivo = get_object_or_404(Cultivo, id=cultivo_id)
    form = AlimentacionForm()
    try:
        alimentacion = Alimentacion.objects.get(dia=hoy, cultivo=cultivo)
    except Alimentacion.DoesNotExist:
        alimentacion = Alimentacion.objects.create(dia=hoy, cultivo=cultivo)

    if request.method == 'POST':
        form = AlimentacionForm(request.POST)
        if form.is_valid:
            f = form.save(commit=False)
            cantidad_gr = form.cleaned_data['cantidad_gr']
            tipo_concentrado = form.cleaned_data['tipo_concentrado']
            f.cantidad_gr = cantidad_gr
            f.tipo_concentrado = tipo_concentrado
            f.responsable = request.user
            f.alimentacion = alimentacion
            f.save()
            concentrado = Concentrado.objects.get(finca=cultivo.finca, nombre=tipo_concentrado)
            concentrado.total_kg = concentrado.total_kg - decimal.Decimal(cantidad_gr/1000)
            concentrado.save()
            messages.info(request, 'ración registrada.')
            return redirect('cultivo_list')
    return render(request, 'control/racion.html', {'form': form, 'alimentacion': alimentacion, 'cultivo': cultivo})


@login_required
def alimentacion_editar(request, cultivo_id, alimentacion_id):
    pass


# ----calidad agua------------------------------------------------------------------------------------------------------
@login_required
def calidad_agua_listar(request, estanque_id):
    estanque = get_object_or_404(Estanque, pk=estanque_id)
    calidad_agua_list = Calidad_agua.objects.filter(estanque_id=estanque_id)

    if request.method == 'POST':
        if request.POST['desde'] is (None or "") and request.POST['hasta'] is not (None or ""):  # 0->x
            fecha_top = datetime.strptime(request.POST.get('hasta'), '%d/%m/%Y')
            if fecha_top.date() < calidad_agua_list.first().fecha_registro.date():
                messages.info(request, 'fecha fuera de rango')
            else:
                fecha_topt = datetime.combine(fecha_top, datetime.max.time()).replace(tzinfo=pytz.UTC)
                calidad_agua_list = calidad_agua_list.filter(fecha_registro__lte=fecha_topt)

        if request.POST['desde'] is not (None or "") and request.POST['hasta'] is (None or ""):  # x->fin
            fecha_bot = datetime.strptime(request.POST.get('desde'), '%d/%m/%Y')
            if fecha_bot.date() > calidad_agua_list.last().fecha_registro.date():
                messages.info(request, 'fecha fuera de rango')
            else:
                fecha_bot = fecha_bot.replace(tzinfo=pytz.UTC)
                calidad_agua_list = calidad_agua_list.filter(fecha_registro__gte=fecha_bot)

        if request.POST['desde'] is not (None or "") and request.POST['hasta'] is not (None or ""):  # x->y
            fecha_top = datetime.strptime(request.POST.get('hasta'), '%d/%m/%Y')
            fecha_bot = datetime.strptime(request.POST.get('desde'), '%d/%m/%Y')
            if fecha_top.date() < fecha_bot.date() or fecha_top.date() < calidad_agua_list.first().fecha_registro.date():
                messages.info(request, 'error de rango')
            else:
                fecha_topt = datetime.combine(fecha_top, datetime.max.time()).replace(tzinfo=pytz.UTC)
                fecha_bot = fecha_bot.replace(tzinfo=pytz.UTC)
                calidad_agua_list = calidad_agua_list.filter(fecha_registro__range=(fecha_bot, fecha_topt))

    context = {
        'estanque': estanque,
        'caliagua_list': calidad_agua_list.order_by('-fecha_registro')
    }
    return render(request, 'control/calidad_agua_list.html', context)


@login_required
def calidad_agua_registrar(request, estanque_id):
    form = CalidadAguaForm()
    estanque = get_object_or_404(Estanque, pk=estanque_id)
    if request.method == 'POST':
        form = CalidadAguaForm(request.POST)
        if form.is_valid():
            caliagua = form.save(commit=False)
            caliagua.estanque = estanque
            caliagua.responsable = request.user
            caliagua.save()
            return redirect('estanque_detalle', estanque_id)
    return render(request, 'control/calidad_agua_registrar.html', {'form': form, 'estanque': estanque})


@login_required
def calidad_agua_editar(request, estanque_id, calidad_agua_id):
    caliagua = get_object_or_404(Calidad_agua, pk=calidad_agua_id)
    form = CalidadAguaForm(request.POST or None, instance=caliagua)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('control:calidad_agua_listar', estanque_id)
    return render(request, 'control/calidad_agua_registrar.html', {"form": form})


@login_required
def calidad_agua_detalle(request, estanque_id, calidad_agua_id):
    estanque = get_object_or_404(Estanque, pk=estanque_id)
    caliagua = get_object_or_404(Calidad_agua, pk=calidad_agua_id)
    return render(request, 'control/calidad_agua_detalle.html', {"caliagua": caliagua, "estanque": estanque})


@login_required
def graficas_agua(request, estanque_id):
    estanque = get_object_or_404(Estanque, pk=estanque_id)
    cali_agua = Calidad_agua.objects.filter(estanque=estanque)
    fechas = []
    oxigeno = []
    temperatura = []
    ph = []
    for c_a in cali_agua:
        oxigeno.append(float(c_a.oxigeno))
        fechas.append(c_a.fecha_registro.strftime('%d-%m-%Y'))
        temperatura.append(float(c_a.temperatura))
        ph.append(float(c_a.ph))

    context = {
        "estanque": estanque,
        "object_list": cali_agua,
        "oxigeno": oxigeno,
        "fechas": fechas,

templates/control/alimentacion_list.html
{% extends 'base.html' %}

{% block title %}
    {{ titulo }}
{% endblock %}

{% block retroceso %}<!-- js página anterior: javascript:window.history.go(-1); -->
{% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    Alimentación - Cultivo: {{ cultivo }}
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m8 offset-m3">
            <a class="btn btn-flat btn-large right" href="{% url 'control:alimentacion_registrar' cultivo.id %}">
                <i class="material-icons right">add</i>
                Alimentar
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m10 offset-m1">
            <table class="striped">
                <thead>
                <tr>
                    <th>Fecha</th>
                    <th>raciones</th>
                    <th>total</th>
                </tr>
                </thead>
                <tbody>
                {% for alimentacion in alimentacion_list %}
                <tr>
                    <td>{{ alimentacion.dia}}</td>
                    <td>{{ alimentacion.racion_set.count }}</td>
                    <td>{{ alimentacion.total }}</td>
                </tr>
                {% empty %}
                    <p class="center">No hay registros de alimentación</p>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/control/calidad_agua_detalle.html
{% extends 'base.html' %}

{% block title %}
    {{ titulo }}
{% endblock %}

{% block retroceso %}<!-- js página anterior: javascript:window.history.go(-1); -->
    {% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    Calidad agua estanque: {{ estanque.nombre }}
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m12">
            <table class="striped highlight">
                <thead>
                </thead>
                <tbody>
                <tr>
                    <td>Fecha:</td>
                    <td>{{ caliagua.fecha_registro }}</td>
                </tr>
                <tr>
                    <td>oxigeno: {</td>
                    <td>{ caliagua.oxigeno }}</td>
                </tr>
                <tr>
                    <td>temperatura: </td>
                    <td>{{ caliagua.temperatura }}</td>
                </tr>
                <tr>
                    <td>pH:</td>
                    <td>{{ caliagua.dureza }}</td>
                </tr>
                 <tr>
                    <td>pH:</td>
                    <td>{{ caliagua.dureza }}</td>
                </tr>
                </tbody>
            </table>
            <br>
            <a class="btn btn-large btn-flat waves-effect right" href="{% url 'cultivo_editar' cultivo.id %}">Editar</a>
        </div>
    </div>
{% endblock %}

templates/control/calidad_agua_list.html
{% extends 'base.html' %}

{% block title %}
    calidad agua
{% endblock %}

{% block retroceso %}<!-- js página anterior: javascript:window.history.go(-1); -->
    {% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    Calidad agua estanque: {{ estanque.nombre }}
{% endblock %}

{% block micontenido %}

    <div class="row">

        <div class="col s12 m4">
            <div class="col s12 m12">
                <small class="italic">Filtro fecha</small>
            </div>
            <form class="" action="." method="post">
                {% csrf_token %}
                <div class="col s12 m6">
                    <label for="desde">Desde</label>
                    <input id="desde" name="desde" type="text" class="datepicker" id="datepicker_custom">
                </div>
                <div class="col s12 m6">
                    <label for="hasta">Hasta</label>
                    <input id="hasta" name="hasta" type="text" class="datepicker" id="datepicker_custom">
                </div>
                <input type="submit" class="btn btn-flat btn-small right" value="filtrar">
            </form>
        </div>
        <div class="col s12 m8">
            <a href="{% url 'control:calidad_agua_registrar' estanque.id %}"
               class="btn btn-large btn-flat waves-effect waves-light right">
                <i class="material-icons right">add</i>
                registrar calidad agua
            </a>
            <a href="{% url 'control:graficas_agua' estanque.id %}"
               class="btn btn-large btn-flat waves-effect waves-light right">
                <i class="material-icons right">insert_chart</i>
                gráficas calidad agua
            </a>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m12 ">
            <table class="striped">
                <thead>
                <tr>
                    <th>Fecha</th>
                    <th>oxigeno</th>
                    <th>temperatura</th>
                    <th>amonio</th>
                </tr>
                </thead>
                <tbody>
                {% for caliagua in caliagua_list %}
                    <tr>
                        <td>
                            <a href="{% url 'control:calidad_agua_detalle' estanque.id caliagua.id %}">{{ caliagua.fecha_registro|date:"d M Y" }}</a>
                        </td>
                        <td>{{ caliagua.oxigeno }}</td>
                        <td>{{ caliagua.temperatura }}</td>
                        <td>{{ caliagua.amonio }}</td>
                        <td><a href="{% url 'control:calidad_agua_editar' estanque.id caliagua.id %}"
                               class="btn btn-small btn-flat waves-effect waves-light right">
                            editar
                        </a></td>
                    </tr>
                {% empty %}
                    <p class="center">No hay registros de calidad de agua</p>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>



{% endblock %}

{% block custom_script %}
    <script>
        $(document).ready(function () {
            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                i18n: {
                    months: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                    monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                    weekdays: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
                    weekdaysShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
                    weekdaysAbbrev: ['d', 'l', 'm', 'm', 'j', 'v', 's']
                }
            });

        });
    </script>
    <script>
        {% if messages %}
            {% for message in messages %}
                M.toast({html: '{{ message }}', classes: 'rounded'});
            {% endfor %}
        {% endif %}
    </script>
{% endblock %}

templates/control/calidad_agua_rangos.html
{% extends 'base.html' %}

{% block title %}
calidad agua - parametros
{% endblock %}

{% block retroceso %}<!-- js página anterior: javascript:window.history.go(-1); -->
{% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    calidad agua / parametros: {{ estanque.nombre }}
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card">
                <div class="card-content ">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <br>
                        <div class="row">
                            <button class="btn btn-large btn-flat waves-effect right" type="submit">
                                <i class="material-icons right">create</i>
                                guardar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/control/calidad_agua_registrar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
registrar-calidad-agua
{% endblock %}

{% block retroceso %}<!-- js página anterior: javascript:window.history.go(-1); -->
{% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    calidad agua estanque: {{ estanque.nombre }}
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card">
                <div class="card-content ">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <br>
                        <div class="row">
                            <button class="btn btn-large btn-flat waves-effect right" type="submit">
                                <i class="material-icons right">create</i>
                                registrar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/control/grafica_muestreo.html
{% extends 'base.html' %}

{% block title %}
    gráfica-talla-peso
{% endblock %}

{% block retroceso %}<!-- js página anterior: javascript:window.history.go(-1); -->
    {% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    Gráfica talla y peso cultivo: {{ cultivo.nombre }}
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m8 offset-m2">
            {% if object_list is None %}
                <p class="center">No hay registros de talla y peso</p>
            {% else %}
                <canvas id="mychart1" width="400" height="200"></canvas>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block custom_script %}
    <script>
        new Chart(document.getElementById("mychart1"), {
            "type": "line",
            "data": {
                "labels": [{% for f in fechas %}"{{ f }}",{% endfor %}],
                "datasets": [{
                    "label": "talla",
                    "data": {{ talla }},
                    "fill": false,
                    "borderColor": "rgb(250, 128, 114)",
                    "lineTension": 0.1
                    },
                    {
                    "label": "peso",
                    "data": {{ peso }},
                    "fill": false,
                    "borderColor": "rgb(75, 192, 192)",
                    "lineTension": 0.1
                    }
                ]
            }, "options": {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        })
    </script>
{% endblock %}

templates/control/mortalidad_registrar.html
{% extends 'base.html' %}

{% block title %}
    registrar-mortalidad
{% endblock %}

{% block retroceso %}<!-- js página anterior: javascript:window.history.go(-1); -->
{% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    Registro Mortalidad (cultivo): {{ cultivo.nombre }}
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m6 offset-m3">
            <div class="card">
                <div class="card-content ">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <br>
                        <div class="row">
                            <button class="btn btn-large btn-flat waves-effect right" type="submit">
                                <i class="material-icons right">create</i>
                                registrar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/control/muestreo_list.html
{% extends 'base.html' %}

{% block title %}
    {{ titulo }}
{% endblock %}

{% block retroceso %}<!-- js página anterior: javascript:window.history.go(-1); -->
{% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    Muestreos del cultivo: {{ cultivo }}
{% endblock %}

{% block micontenido %}

    <div class="row">
        <div class="col s12 m10 offset-m1">
            <a class="btn btn-flat btn-large right" href="{% url 'control:muestreo_registrar' cultivo.id %}"><i
                    class="material-icons right">add</i>Nuevo
                muestreo</a>
            <a class="btn btn-flat btn-large right" href="{% url 'control:grafica_muestro' cultivo.id %}"><i
                    class="material-icons right">insert_chart</i>Gráfica talla y peso</a>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m8 offset-m2">
            <table class="striped">

                <thead>
                <tr>
                    <th>Fecha</th>
                    <th>peso promedio gr</th>
                    <th>talla promedio cm</th>
                </tr>
                </thead>

                <tbody>
                {% for muestreo in muestreo_list %}
                    <tr>
                        <td><a href="{% url 'control:muestreo_detalle' cultivo.id muestreo.id %}">{{ muestreo.fecha_registro }}</a></td>
                        <td>{{ muestreo.peso_promedio_gr }}</td>
                        <td>{{ muestreo.talla_promedio_cm }}</td>
                    </tr>
                {% empty %}
                    <div class="center">
                        <small>No se han registrado muestreos</small>
                    </div>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>
{% endblock %}

templates/control/racion.html
{% extends 'base.html' %}

{% block title %}
    {{ titulo }}
{% endblock %}

{% block retroceso %}<!-- js página anterior: javascript:window.history.go(-1); -->
    {% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    Ración: {{ alimentacion.dia }}
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card">
                {% if messages %}
                    {% for message in  messages %}
                        {{ message }}
                    {% endfor %}
                {% endif %}
                <div class="card-content ">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="row">
                            <button class="btn btn-large btn-flat waves-effect right" type="submit">
                                <i class="material-icons right">create</i>
                                registrar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}