RegistroPiscicola/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pagina.urls')),
    path('',include('registro.urls')),
    path('',include('control.urls')),
    path('',include('inventario.urls')),
    path('',include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

control/urls.py
from django.urls import path
from .views import *

app_name = 'control'

urlpatterns = [
    # ----muestreo
    path('cultivos/<int:cultivo_id>/muestreos/', muestreo_listar, name='muestreo_listar'),
    path('cultivos/<int:cultivo_id>/muestreos/grafica/', grafica_muestreo, name='grafica_muestro'),
    path('cultivos/<int:cultivo_id>/muestreos/registrar/', muestreo_registrar, name='muestreo_registrar'),
    path('cultivos/<int:cultivo_id>/muestreos/<int:muestreo_id>/editar/', muestreo_editar, name='muestreo_editar'),
    path('cultivos/<int:cultivo_id>/muestreos/<int:muestreo_id>/', muestreo_detalle, name='muestreo_detalle'),
    path('cultivos/<int:cultivo_id>/mortalidad/', mortalidad_registrar, name='mortalidad_registrar'),
    # ----alimentacion
    path('cultivos/<int:cultivo_id>/alimentacion/', alimentacion_listar, name='alimentacion_listar'),
    path('cultivos/<int:cultivo_id>/alimentacion/registrar/', alimentacion_registrar, name='alimentacion_registrar'),
    path('cultivos/<int:cultivo_id>/alimentacion/<int:alimentacion_id>/editar/', alimentacion_editar,
         name='alimentacion_editar'),
    # ----calidad agua
    path('estanques/<int:estanque_id>/calidad_agua/', calidad_agua_listar, name='calidad_agua_listar'),
    path('estanques/<int:estanque_id>/calidad_agua/registrar/', calidad_agua_registrar,
         name='calidad_agua_registrar'),
    path('estanques/<int:estanque_id>/calidad_agua/<int:calidad_agua_id>/', calidad_agua_detalle,
         name='calidad_agua_detalle'),
    path('estanques/<int:estanque_id>/calidad_agua/<int:calidad_agua_id>/editar/', calidad_agua_editar,
         name='calidad_agua_editar'),
    path('estanques/<int:estanque_id>/calidad_agua/graficas_agua/', graficas_agua, name='graficas_agua'),
    path('estanques/calidad_agua_rangos/', calidad_agua_rangos_create, name='calidad_agua_rangos_create'),
]

inventario/urls.py
from django.urls import path
from .views import *

app_name = 'inventario'

urlpatterns = [
    path('concentrado/', concentrado_list, name='concentrado_list'),
    path('concentrado/nuevo/', concentrado_create, name='concentrado_create'),
    path('concentrado/comprabultos/nuevo/', compra_bultos_create, name='compra_bultos_create'),
    path('concentrado/comprabultos/', compra_bultos_list, name='compra_bultos_list'),
]

registro/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('piscicola/', la_piscicola, name='la_piscicola'),
    path('cosechas/', cosecha_list, name='cosecha_list'),
    # --------------------------------------------------------------------------------------
    path('estanques/', estanque_list, name='estanque_list'),
    path('estanques/crear/', estanque_crear, name='estanque_crear'),
    path('estanques/<int:estanque_id>/',estanque_detalle, name='estanque_detalle'),
    path('estanques/<int:estanque_id>/editar/', estanque_editar, name='estanque_editar'),
    # --------------------------------------------------------------------------------------
    path('cultivos/', cultivo_list, name='cultivo_list'),
    path('cultivos/crear/',cultivo_crear, name='cultivo_crear'),
    path('cultivos/<int:cultivo_id>/',cultivo_detalle, name='cultivo_detalle'),
    path('cultivos/<int:cultivo_id>/editar/', cultivo_editar, name='cultivo_editar'),
    path('cultivos/<int:cultivo_id>/cosechar/', cultivo_cosechar, name='cultivo_cosechar'),
]

users/urls.py
from django.urls import path
from users import views as user_views
from django.contrib.auth.decorators import login_required

# Python Django Tutorial: Full-Featured Web App Part 7 - Login and Logout System
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('registrar/', user_views.registrar, name='registrar'),
    path('ingresar/', auth_views.LoginView.as_view(template_name='users/ingresar.html'), name='ingresar'),
    path('salir/', auth_views.LogoutView.as_view(template_name='users/salir.html'), name='salir'),
    path('perfil/', user_views.perfil, name='perfil'),
]

registro/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from django.core.validators import MinValueValidator
from django.urls import reverse
from django.db.models.signals import pre_save
from django.dispatch import receiver


class Finca(models.Model):
    razon_social = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    def __str__(self):
        return self.razon_social

    def save(self, *args, **kwargs):
        self.slug = slugify(self.razon_social)
        super(Finca, self).save(*args, **kwargs)


# ----------------------------------------------------------------------------------------------------------------------
class Estanque(models.Model):
    nombre = models.CharField(max_length=100)
    tipo = models.CharField(max_length=100)
    nivel_agua_mts = models.DecimalField(max_digits=5, decimal_places=2,
                                         validators=[MinValueValidator(0)])
    mts_2 = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(0)])
    detalle = models.TextField(blank=True, null=True)
    # --------------------------------------------------------------------------------------
    finca = models.ForeignKey(Finca, on_delete=models.CASCADE, blank=True)
    responsable = models.CharField(max_length=100)
    fecha_registro = models.DateTimeField(default=timezone.now)
    fecha_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

    # class Meta:
    #     unique_together = (
    #        ('finca', 'nombre'),
    #     )


# ----------------------------------------------------------------------------------------------------------------------
class Cultivo(models.Model):
    CHOICES = (('siembra', 'siembra'), ('levante', 'levante'), ('engorde', 'engorde'))
    nombre = models.CharField(max_length=100)
    estanque = models.ForeignKey(Estanque, on_delete=models.SET_NULL, null=True)
    especie = models.CharField(max_length=50, default='tilapia')
    cantidad = models.PositiveIntegerField(validators=[MinValueValidator(0)])
    tamaño_pez_cm = models.DecimalField(max_digits=5, decimal_places=1, validators=[MinValueValidator(0)])
    peso_pez_gr = models.DecimalField(max_digits=5, decimal_places=1, validators=[MinValueValidator(0)])
    densidad_inicial = models.PositiveSmallIntegerField(blank=True, null=True)
    etapa = models.CharField(max_length=7, choices=CHOICES, default='siembra')
    detalle = models.TextField(blank=True, null=True)
    # ----
    finca = models.ForeignKey(Finca, on_delete=models.CASCADE)
    responsable = models.CharField(max_length=100)
    cosechado = models.BooleanField(default=False)
    fecha_registro = models.DateTimeField(default=timezone.now)
    fecha_cosecha = models.DateTimeField(blank=True, null=True)
    fecha_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('cultivo_detalle', kwargs={'cultivo_id': self.id})  # f"/products/{self.id}/"

    def total_peces(self):
        total_muertes = 0
        for mortalidad in self.mortalidad_set.all():
            total_muertes += mortalidad.peces_muertos
        return self.cantidad - total_muertes

    def alimento_promedio(self):
        """alimento promedio diario"""
        alimento_total = 0
        alimentacion = self.alimentacion_set.all()
        numero_elementos = alimentacion.count()
        if numero_elementos == 0:
            return 0
        else:
            for alimentacion in alimentacion:
                alimento_total += alimentacion.total()
            promedio = alimento_total / numero_elementos
            return promedio


# @receiver(pre_save, sender=Cultivo)
# def calculos_muestreo(sender, instance, *args, **kwargs):

registro/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import EstanqueCreateForm, EstanqueEditForm, CultivoCreateForm, CultivoEditForm
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.views.generic import ListView,CreateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime

@login_required
def la_piscicola(request):  # página inicial logeado
    la_piscicola_obj = request.user.profile.trabaja_en
    print(request.user.profile.trabaja_en)
    if la_piscicola_obj is not None:
        if 'la_piscicola' not in request.session:
            request.session['la_piscicola'] = la_piscicola_obj.id
    # raise Http404("Este usuario no tiene un finca asignada")
    else:
        messages.error(request, 'el usuario no esta asignado a ninguna finca')
    context = {
        'la_piscicola': la_piscicola_obj
    }
    return render(request, 'registro/la_piscicola.html', context)

# ----estanque views----------------------------------------------------------------------------------------------------
@login_required
def estanque_list(request):
    finca = None
    lista = None
    if request.user.is_authenticated:
        # print(request.session['la_piscicola'])
        finca = request.user.profile.trabaja_en
        #                               finca__id=request.session['la_piscicola']
        lista = Estanque.objects.filter(finca=finca).order_by('-fecha_registro')
        mensaje = 'consulta exitosa'
        if finca is None:
            mensaje = 'no perteneces a ninguna finca consulta con el administrador'
    else:
        mensaje='error: no ha iniciado sesión'
    context = {
        'la_piscicola': finca,
        'titulo': 'Mis estanques',
        'estanques': lista,
        'mensaje': mensaje
    }
    return render(request, 'registro/estanque_list.html', context)


@login_required
def estanque_crear(request):
    if request.method == 'POST':
        form = EstanqueCreateForm(request.POST or None)
        if form.is_valid():
            estanque = form.save(commit=False)
            estanque.finca = request.user.profile.trabaja_en
            estanque.responsable = request.user
            estanque.save()
            return redirect('estanque_list')
    else:
        form = EstanqueCreateForm()
    context={
        'form': form,
        'titulo': ' Nuevo estanque'
    }
    return render(request, 'registro/estanque_crear.html', context)


@login_required
def estanque_detalle(request, estanque_id):
    estanque = get_object_or_404(Estanque, pk=estanque_id)
    return render(request,'registro/estanque_detalle.html', {'estanque': estanque})


@login_required
def estanque_editar(request, estanque_id):
    objeto = get_object_or_404(Estanque, pk=estanque_id)
    form = EstanqueEditForm(request.POST or None, instance=objeto, estanque_id=estanque_id)
    if form.is_valid():
        form.save()
        return redirect('estanque_detalle', estanque_id)
    context = {
        'form': form,
        'titulo': 'Editar estanque'
    }
    return render(request, 'registro/estanque_crear.html', context)


# ----cultio views------------------------------------------------------------------------------------------------------
@login_required
def cultivo_list(request):
    finca = None
    lista = None
    if request.user.is_authenticated:
        finca = request.user.profile.trabaja_en
        lista = Cultivo.objects.filter(finca=finca, cosechado=False).order_by('-fecha_registro')
        mensaje = 'consulta exitosa'
        if finca is None:
            mensaje = 'tu cuenta no esta asociada a ninguna finca consulta con el administrador'
    else:
        mensaje='error: no ha iniciado sesión'

    context = {
        'la_piscicola': finca,
        'titulo': 'Mis cultivos',
        'cultivos': lista,
        'mensaje': mensaje
    }
    return render(request, 'registro/cultivo_list.html', context)


@login_required
def cultivo_crear(request):
    form = CultivoCreateForm()
    if request.method == 'POST':
        form = CultivoCreateForm(request.POST)
        if form.is_valid():
            cultivo = form.save(commit=False)
            cultivo.finca = request.user.profile.trabaja_en
            cultivo.responsable = request.user
            peso = form.cleaned_data['peso_pez_gr']
            if 40 < peso < 120:
                cultivo.etapa = "levante"
                cultivo.save()
            if peso >= 120:
                cultivo.etapa = "engorde"
                cultivo.save()
            else:
                cultivo.save()
            return redirect('cultivo_list')
    context = {
        'form': form,
        'titulo': 'Nuevo cultivo'
    }
    return render(request, 'registro/cultivo_crear.html', context)


@login_required
def cultivo_detalle(request, cultivo_id):
    try:
        cultivo = Cultivo.objects.get(pk=cultivo_id)
    except Cultivo.DoesNotExist:
        raise Http404("no existe ese cultivo")
    return render(request, 'registro/cultivo_detalle.html', {'cultivo': cultivo})


@login_required
def cultivo_editar(request, cultivo_id):
    objeto = get_object_or_404(Cultivo, pk=cultivo_id)
    form = CultivoEditForm(request.POST or None, instance=objeto, cultivo_id=cultivo_id)
    if request.method == 'POST':
        print(form.errors)
        if form.is_valid():
            print('es valido')
            cultivo = form.save(commit=False)
            peso = cultivo.peso_pez_gr
            if 40 < peso < 120:
                cultivo.etapa = "levante"
                cultivo.save()
            if peso >= 120:
                cultivo.etapa = "engorde"
                cultivo.save()
            else:
                cultivo.save()
            return redirect('cultivo_detalle', cultivo_id)
    context = {
        'form': form,
        'titulo': 'Editar cultivo'
    }
    return render(request, 'registro/cultivo_crear.html', context)


@login_required
def cosecha_list(request):
    finca = None
    lista = None
    if request.user.is_authenticated:
        finca = request.user.profile.trabaja_en
        lista = Cultivo.objects.filter(finca=finca, cosechado=True).order_by('-fecha_update')
        mensaje = 'consulta exitosa'
        if finca is None:
            mensaje = 'tu cuenta no esta asociada a ninguna finca consulta con el administrador'
    else:
        mensaje = 'error: no ha iniciado sesión'

    context = {
        'la_piscicola': finca,
        'titulo': 'Mis cosechas',
        'cosechas': lista,
        'mensaje': mensaje
    }
    return render(request, 'registro/cosecha_list.html', context)


def cultivo_cosechar(request, cultivo_id):
    cultivo = Cultivo.objects.get(pk=cultivo_id)
    if request.method == 'POST':
        cultivo.cosechado = True
        cultivo.fecha_cosecha = datetime.now()
        cultivo.save()
        return redirect('cosecha_list')
    context = {
        'cultivo': cultivo,
    }
    return render(request, 'registro/cultivo_cosechar.html', context)

templates/registro/color_etapa.html
{% load static %}

{% if cultivo.cocechado %}
    <i class="material-icons light-blue-text text-accent-2">brightness_1</i>
{% elif cultivo.etapa == 'siembra' %}
     <i class="material-icons orange-text text-accent-2">brightness_1</i>
{% elif cultivo.etapa == 'levante' %}
    <i class="material-icons yellow-text ">brightness_1</i>
{% elif cultivo.etapa == 'engorde' %}
    <i class="material-icons green-text ">brightness_1</i>
{% endif %}

templates/registro/cosecha_list.html
{% extends 'base.html' %}

{% block title %}
    {{ titulo }}
{% endblock %}

{% block retroceso %}
<a href="/piscicola" class="btn-floating btn-small waves-effect waves-light blue darken-4"><i class="material-icons">arrow_back</i></a>
{% endblock %}

{% block main_title %}
    <span class="margin-derecha">{{ titulo }}</span>
{% endblock %}

{% block micontenido %}

    {% if cosechas %}
        <div class="row center">
            <small class="orange-text text-accent-2">total cosechas: {{ cosechas|length }}</small>
        </div>

        <div class="row">
            <div class="col s12 m10 offset-m1">
            <table class="striped">
                <thead>
                <tr>
                    <th>Nombre:</th>
                    <th>fecha cosecha:</th>
                    <th>numero de peces:</th>
                </tr>
                </thead>
                <tbody>
                {% for cosecha in cosechas %}
                <tr>
                    <td>{{ cosecha.nombre}}</td>
                    <td>{{ cosecha.fecha_cosecha}}</td>
                    <td>{{ cosecha.total_peces }}</td>
                </tr>
                {% empty %}
                    <p class="center">No se han registrado muestreos</p>
                {% endfor %}
                </tbody>
            </table>
        </div>

        </div>

    {% else %}
        <p>No se han registrado cosechas</p>
    {% endif %}

{% endblock %}

templates/registro/cultivo_cosechar.html
{% extends 'base.html' %}
{% block title %}
    Confirmar cosecha
{% endblock %}

{% block main_title %}
    Confirmar cosecha
{% endblock %}

{% block micontenido %}
    <br>
<form class="center" action="." method="POST">
    {% csrf_token %}
    <h4>¿seguro que desea realizar la cocecha del cultivo: {{ cultivo.nombre }}?</h4>
    <input class="btn light-blue" type="submit" value="si"><a class="btn btn-flat" href="../../">regresar</a>
</form>

{% endblock %}

templates/registro/cultivo_crear.html
{% extends 'base.html' %}

{% block title %}
    registrar-cultivo
{% endblock %}

{% block retroceso %}
    {% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    <span class="margin-derecha">{{ titulo }}</span>
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card">
                {% if messages %}
                    {% for message in  messages %}
                        {{ message }}
                    {% endfor %}
                {% endif %}
                <div class="card-content ">

                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <br>
                        <div class="red-text" id="select-error"></div>
                        <div class="row">
                            <button class="btn btn-large btn-flat waves-effect right validar" type="submit">
                                <i class="material-icons right">create</i>
                                registrar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block custom_script %}
    <script>
        $(document).ready(function () {
            $('.validar').click(function () {
                console.log('hola')
                select = $("#id_estanque option:selected").text()
                if (select == '---------') {
                    $('#select-error').html('<p>por favor seleccione un estanque</p>')
                }

            })
            /* $('input').parent().attr('class', 'input-field');*/
        });

    </script>
{% endblock %}

templates/registro/cultivo_detalle.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    cultivo: {{ cultivo.nombre }}
{% endblock %}

{% block retroceso %}<!-- js página anterior: javascript:window.history.go(-1); -->
    {% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    <span class="margin-derecha">Cultivo: {{ cultivo.nombre }}</span>
{% endblock %}

{% block micontenido %}

    <div class="center">
        <small class="orange-text text-accent-2">Alimento promedio diario: {{ cultivo.alimento_promedio }} gr</small>
    </div>
    <div class="row">
        <div class="col s12 m8 offset-m3">
            <a class="btn btn-flat btn-large right" href="{% url 'control:muestreo_listar' cultivo.id %}"><i
                    class="material-icons right">insert_chart</i>Muestreo</a>
            <a class="btn btn-flat btn-large right" href="{% url 'control:alimentacion_listar' cultivo.id %}"><i
                    class="material-icons right">insert_chart</i>Alimentación</a>
            <a class="btn btn-flat btn-large right" href="{% url 'control:mortalidad_registrar' cultivo.id %}"><i
                    class="material-icons right">insert_chart</i>Mortalidad</a>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col s12 m12">
            <table class="striped highlight">
                <thead>
                </thead>
                <tbody>
                <tr>
                    <td>estanque:</td>
                    <td>{{ cultivo.estanque }}</td>
                </tr>
                <tr>
                    <td>especie:</td>
                    <td>{{ cultivo.especie }}</td>
                </tr>
                <tr>
                    <td>cantidad inicial:</td>
                    <td>{{ cultivo.cantidad }}</td>
                </tr>
                <tr>
                    <td>total peces:</td>
                    <td>{{ cultivo.total_peces }}</td>
                </tr>
                <tr>
                    <td>tamaño pez (cm):</td>
                    <td>{{ cultivo.tamaño_pez_cm }}</td>
                </tr>
                <tr>
                    <td>peso pez (gr):</td>
                    <td>{{ cultivo.peso_pez_gr }}</td>
                </tr>
                <tr>
                    <td>densidad inicial (peces/m2):</td>
                    <td>{{ densidad_inicial }}</td>
                </tr>
                <tr>
                    <td>etapa:</td>
                    <td>{{ cultivo.etapa }}</td>
                </tr>
                <tr>
                    <td>responsable:</td>
                    <td>{{ cultivo.responsable }}</td>
                </tr>
                <tr>
                    <td>fecha registro:</td>
                    <td>{{ cultivo.fecha_registro }}</td>
                </tr>
                <tr>
                    <td>fecha modificado:</td>
                    <td>{{ cultivo.fecha_update }}</td>
                </tr>
                <tr>
                    <td>detalle:</td>
                    <td>{{ cultivo.detalle }}</td>
                </tr>
                </tbody>
            </table>
            <br>
            <a class="btn btn-large btn-flat waves-effect right" href="{% url 'cultivo_editar' cultivo.id %}">
                <i class="material-icons right">create</i>
                Editar
            </a>
            <a class="btn btn-large btn-flat waves-effect left" href="{% url 'cultivo_cosechar' cultivo.id %}">
                <i class="material-icons left">thumb_up</i>
                Cocechar
            </a>
        </div>
    </div>

{% endblock %}

{% block custom_script %}
    <script>
        {% if messages %}
                {% for message in messages %}
                    M.toast({html: '{{ message }}', classes: 'rounded'})
                {% endfor %}
            {% endif %}
    </script>
{% endblock %}

templates/registro/cultivo_list.html
{% extends 'base.html' %}

{% block title %}
    {{ titulo }}
{% endblock %}

{% block retroceso %}
    <a href="/piscicola" class="btn-floating btn-small waves-effect waves-light blue darken-4"><i
            class="material-icons">arrow_back</i></a>
{% endblock %}

{% block main_title %}
    <span class="margin-derecha">{{ titulo }}</span>
{% endblock %}

{% block micontenido %}

    {% if cultivos %}
        <div class="center">
            <small class="orange-text text-accent-2">número de cultivos: {{ cultivos|length }}</small>
        </div>
    {% endif %}

    <div class="row">
        <a href="{% url 'cultivo_crear' %}" class="btn btn-large btn-flat waves-effect waves-light right">
            <i class="material-icons right">add</i>
            nuevo cultivo
        </a>
        <a href="{% url 'cosecha_list' %}" class="btn btn-large btn-flat waves-effect waves-light right">
            <i class="material-icons right">format_list_bulleted</i>
            cosechas
        </a>
    </div>

    {% if cultivos %}
        <div class="row">
            <ul>
                {% for cultivo in cultivos %}
                    <li class="col s12 m6">
                        <div class="card">
                            <div class="card-content">
                                <span class="card-title">
                                    {{ cultivo.nombre }}
                                    <span class="right">{% include 'registro/color_etapa.html' %}</span>
                                </span>

                            </div>
                            <div class="card-action">
                                <a class="valign-wrapper blue-text text-darken-4" href="{{ cultivo.get_absolute_url }}">
                                    <i class="material-icons right blue-text text-darken-4">description</i>Detalles</a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>

    {% else %}
        <p>No se han registrado cultivos</p>
    {% endif %}

{% endblock %}

{% block custom_script %}
    <script>
        {% if messages %}
            {% for message in messages %}
                M.toast({html: '{{ message }}', classes: 'rounded'})
            {% endfor %}
        {% endif %}
    </script>
{% endblock %}

templates/registro/estanque_crear.html
{% extends 'base.html' %}

{% block title %}
    registrar-estanque
{% endblock %}

{% block retroceso %}
{% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    <span class="margin-derecha">{{ titulo }}</span>
{% endblock %}

{% block micontenido %}

    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card">
                <div class="card-content ">
                    <form method="post" action=".">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <br>
                        <div class="row">
                            <button class="btn btn-large btn-flat waves-effect waves-light right" type="submit">
                                <i class="material-icons right">create</i>
                                registrar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/registro/estanque_detalle.html
{% extends 'base.html' %}

{% block title %}
    estanque: {{ estanque.nombre }}
{% endblock %}

{% block retroceso %}
{% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    <span class="margin-derecha">Estanque: {{ estanque.nombre }}</span>
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m8 offset-m3">
            <a class="btn btn-flat btn-large right waves-effect waves-light"
               href="{% url 'control:calidad_agua_listar' estanque.id %}">
                <i class="material-icons right">insert_chart</i>Calidad - agua</a>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col s12 m12">
            <table class="striped">
                <thead>
                </thead>
                <tbody>
                <tr>
                    <td>Tipo:</td>
                    <td>{{ estanque.tipo }}</td>
                </tr>
                <tr>
                    <td>Nivel agua (mts):</td>
                    <td>{{ estanque.nivel_agua_mts }}</td>
                </tr>
                <tr>
                    <td>Area (mts2):</td>
                    <td>{{ estanque.mts_2 }}</td>
                </tr>
                <tr>
                    <td>Responsable:</td>
                    <td>{{ estanque.responsable }}</td>
                </tr>
                <tr>
                    <td>Fecha de registro:</td>
                    <td>{{ estanque.fecha_registro }}</td>
                </tr>
                <tr>
                    <td>Fecha de modificación:</td>
                    <td>{{ estanque.fecha_update }}</td>
                </tr>
                <tr>
                    <td>detalle:</td>
                    <td>{{ estanque.detalle }}</td>
                </tr>
                </tbody>
            </table>
            <br>
            <a class="btn btn-large btn-flat waves-effect right" href="{% url 'estanque_editar' estanque.id%}">
                <i class="material-icons right">create</i>
                Editar
            </a>
        </div>
    </div>
{% endblock %}

templates/registro/la_piscicola.html
{% extends 'base.html' %}

{% block title %}
   Piscícola: {% if la_piscicola %}{{ la_piscicola.razon_social }} {% endif %}
{% endblock %}

{% block main_title %}
    Piscícola: {% if la_piscicola %}{{ la_piscicola.razon_social }} {% endif %}
{% endblock %}

{% block micontenido %}
    <div class="center">
        {% if la_piscicola %}
            <div class="row">
            <div class="col s12 m4">
                <a class="nowrap btn btn-flat btn-large full_ancho_m" href="{% url 'cultivo_list' %}">
                    <span class="">Mis Cultivos</span>
                </a>
            </div>
            <div class="col s12 m4">
                <a class="nowrap btn btn-flat btn-large full_ancho_m" href="{% url 'estanque_list' %}">
                    <span>Mis Estanques</span>
                </a>
            </div>
            <div class="col s12 m4">
                <a class="nowrap btn btn-flat btn-large full_ancho_m" href="{% url 'inventario:concentrado_list' %}">
                    <span class="">Mi Concentrado</span>
                </a>
            </div>
            </div>
        {% else %}
            <p class="flow-text">No has configurado tu finca, comunícate con el administrador</p>
        {% endif %}
    </div>


{% endblock %}