RegistroPiscicola/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pagina.urls')),
    path('',include('registro.urls')),
    path('',include('control.urls')),
    path('',include('inventario.urls')),
    path('',include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventario/urls.py
from django.urls import path
from .views import *

app_name = 'inventario'

urlpatterns = [
    path('concentrado/', concentrado_list, name='concentrado_list'),
    path('concentrado/nuevo/', concentrado_create, name='concentrado_create'),
    path('concentrado/comprabultos/nuevo/', compra_bultos_create, name='compra_bultos_create'),
    path('concentrado/comprabultos/', compra_bultos_list, name='compra_bultos_list'),
]

users/urls.py
from django.urls import path
from users import views as user_views
from django.contrib.auth.decorators import login_required

# Python Django Tutorial: Full-Featured Web App Part 7 - Login and Logout System
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('registrar/', user_views.registrar, name='registrar'),
    path('ingresar/', auth_views.LoginView.as_view(template_name='users/ingresar.html'), name='ingresar'),
    path('salir/', auth_views.LogoutView.as_view(template_name='users/salir.html'), name='salir'),
    path('perfil/', user_views.perfil, name='perfil'),
]

inventario/models.py
from django.db import models
from django.utils import timezone
from registro.models import Finca


class Concentrado(models.Model):
    """Para registrar los tipos de concentrado a utilizar"""
    nombre = models.CharField(max_length=100)
    proteina = models.PositiveSmallIntegerField('Proteina %')
    kilos = models.PositiveSmallIntegerField()
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    total_kg = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    detalle = models.TextField(blank=True, null=True)
    # ----
    finca = models.ForeignKey(Finca, on_delete=models.CASCADE)
    responsable = models.CharField(max_length=100)
    fecha_registro = models.DateTimeField(default=timezone.now)
    fecha_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.nombre)


class CompradeBultos(models.Model):
    """Para registrar las cantidades de concentrado comprado"""
    concentrado = models.ForeignKey(Concentrado, on_delete=models.CASCADE)
    numero_bultos = models.PositiveSmallIntegerField()
    precio_unidad = models.DecimalField(max_digits=8, decimal_places=2)
    # ----
    finca = models.ForeignKey(Finca, on_delete=models.CASCADE)
    responsable = models.CharField(max_length=100)
    fecha_registro = models.DateTimeField(default=timezone.now)
    fecha_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "bultos {}".format(self.concentrado)

    def total_compra(self):
        return self.numero_bultos * self.precio_unidad

inventario/forms.py
from django import forms
from .models import *
from cuser.middleware import CuserMiddleware


class ConcentradoForm(forms.ModelForm):
    class Meta:
        model = Concentrado
        fields = ['nombre', 'proteina', 'kilos', 'precio', 'detalle']

    def clean_nombre(self, *args, **kwargs):
        user = CuserMiddleware.get_user()
        coincidencias = Concentrado.objects.filter(finca=user.profile.trabaja_en, nombre=self.nombre).count()
        nombre = self.cleaned_data.get('nombre')
        if coincidencias == 0:
            return nombre
        else:
            raise forms.ValidationError('ya existe un elemento con ese nombre')


class CompraBultosForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CompraBultosForm, self).__init__(*args, **kwargs)
        user = CuserMiddleware.get_user()
        self.fields['concentrado'] = forms.ModelChoiceField(
            queryset=Concentrado.objects.filter(finca=user.profile.trabaja_en))

    class Meta:
        model = CompradeBultos
        fields = ['concentrado', 'numero_bultos', 'precio_unidad']

inventario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ConcentradoForm, CompraBultosForm
from .models import Concentrado, CompradeBultos


# Create your views here.
@login_required
def concentrado_list(request):
    concentrados = Concentrado.objects.filter(finca=request.user.profile.trabaja_en)
    context = {
        'concentrados': concentrados
    }
    return render(request, 'inventario/concentrado_list.html', context)


@login_required
def concentrado_create(request):
    if request.method == 'POST':
        form = ConcentradoForm(request.POST or None)
        if form.is_valid():
            concentrado = form.save(commit=False)
            concentrado.finca = request.user.profile.trabaja_en
            concentrado.responsable = request.user
            concentrado.save()
            return redirect('inventario:concentrado_list')
    else:
        form = ConcentradoForm()
    context = {
        'form': form,
    }
    return render(request, 'inventario/concentrado_create.html', context)

@login_required
def compra_bultos_create(request):
    if request.method == 'POST':
        form = CompraBultosForm(request.POST or None)
        if form.is_valid():
            bultos = form.cleaned_data['numero_bultos']
            tipo_concentrado = form.cleaned_data['concentrado']
            compra = form.save(commit=False)
            compra.finca = request.user.profile.trabaja_en
            compra.responsable = request.user
            compra.save()
            concentrado = Concentrado.objects.get(finca=request.user.profile.trabaja_en, nombre=tipo_concentrado)
            concentrado.total_kg = concentrado.total_kg + (bultos*concentrado.kilos)
            concentrado.save()
            return redirect('inventario:concentrado_list')
    else:
        form = CompraBultosForm()
    context = {
        'form': form,
    }
    return render(request, 'inventario/compra_bultos_create.html', context)


@login_required
def compra_bultos_list(request):
    concentrado_comprado = CompradeBultos.objects.filter(finca=request.user.profile.trabaja_en)
    total = 0
    for compra in concentrado_comprado:
        total += compra.total_compra()
    context = {
        'concentrado_comprado': concentrado_comprado,
        'total': total
    }
    return render(request, 'inventario/compra_bultos_list.html', context)

templates/inventario/compra_bultos_create.html
{% extends 'base.html' %}

{% block title %}
    registrar-entrada-concentrado
{% endblock %}

{% block retroceso %}
    {% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    Entrada de concentrado
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card">
                <div class="card-content ">
                    <p class="small italic">Si no aparece el tipo de concentrado, crear primero <a href="{% url 'inventario:concentrado_create' %}">aquí</a></p>
                    <br>
                    <form method="post">
                        {% csrf_token %}
                            {{ form.as_p}}
                        <br>
                        <div class="row">
                            <button class="btn btn-large btn-flat waves-effect right" type="submit">
                                <i class="material-icons right">create</i>
                                registrar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/inventario/compra_bultos_list.html
{% extends 'base.html' %}

{% block title %}
    Concentrado comprado
{% endblock %}

{% block retroceso %}<!-- js página anterior: javascript:window.history.go(-1); -->
{% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    Concentrado comprado
{% endblock %}

{% block micontenido %}
    <div class="row center">
        <small class="orange-text text-accent-2">total: ${{ total }}</small>
    </div>
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <table class="striped">

                <thead>
                <tr>
                    <th>Fecha</th>
                    <th>tipo</th>
                    <th>bultos</th>
                    <th>$ precio</th>
                    <th>$ total</th>
                </tr>
                </thead>

                <tbody>
                {% for compra in concentrado_comprado %}
                    <tr>
                        <td><a href="">{{ compra.fecha_registro }}</a></td>
                        <td>{{ compra.concentrado }}</td>
                        <td>{{ compra.numero_bultos }}</td>
                        <td>{{ compra.precio_unidad }}</td>
                        <td>{{ compra.total_compra }}</td>
                    </tr>
                {% empty %}
                    <div class="center">
                        <small>No se han registrado compras</small>
                    </div>
                {% endfor %}
                </tbody>

            </table>
        </div>
    </div>
{% endblock %}

templates/inventario/concentrado_create.html
{% extends 'base.html' %}

{% block title %}
    registrar-producto-concentrado
{% endblock %}

{% block retroceso %}
    {% include 'retroceso.html' %}
{% endblock %}

{% block main_title %}
    Producto concentrado
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card">
                <div class="card-content ">
                    <form method="post">
                        {% csrf_token %}
                            {{ form.as_p}}
                        <br>
                        <div class="row">
                            <button class="btn btn-large btn-flat waves-effect right" type="submit">
                                <i class="material-icons right">create</i>
                                registrar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/inventario/concentrado_list.html
{% extends 'base.html' %}

{% block title %}
    Concentrado
{% endblock %}

{% block retroceso %}
    <a href="/piscicola" class="btn-floating btn-small waves-effect waves-light blue darken-4"><i
            class="material-icons">arrow_back</i></a>
{% endblock %}

{% block main_title %}
    <span class="margin-derecha">Mi concentrado</span>
{% endblock %}

{% block micontenido %}

    {% if concentrados %}
        <div class="center">
            <small class="orange-text text-accent-2">tipos de concentrados: {{ concentrados|length }}</small>
        </div>
    {% endif %}

    <div class="row">
        <a href="{% url 'inventario:concentrado_create' %}"
           class="btn btn-large btn-flat waves-effect waves-light right">
            <i class="material-icons right">add</i>
            nuevo tipo concentrado
        </a>
        <a href="{% url 'inventario:compra_bultos_create' %}"
           class="btn btn-large btn-flat waves-effect waves-light right">
            <i class="material-icons right">add</i>
            nuevo entrada de concentrado
        </a>
        <a href="{% url 'inventario:compra_bultos_list' %}"
           class="btn btn-large btn-flat waves-effect waves-light right">
            <i class="material-icons right">format_list_bulleted</i>
            listado de compras
        </a>
    </div>

    {% if concentrados %}
        <div class="row">
            <ul>
                {% for concentrado in concentrados %}
                    <li class="col s12 m6">
                        <div class="card">
                            <div class="card-content">
                                <p class="card-title">{{ concentrado.nombre }}
                                    <span class="flow-text right">{{ concentrado.total_kg }}Kg</span>
                                </p>
                            </div>
                            <div class="card-action">
                                <a class="valign-wrapper blue-text text-darken-4" href="#">
                                    <i class="material-icons right blue-text text-darken-4">description</i>Detalles</a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        <p>No se han registrado concentrados</p>
    {% endif %}
{% endblock %}