RegistroPiscicola/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pagina.urls')),
    path('',include('registro.urls')),
    path('',include('control.urls')),
    path('',include('inventario.urls')),
    path('',include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

control/urls.py
from django.urls import path
from .views import *

app_name = 'control'

urlpatterns = [
    # ----muestreo
    path('cultivos/<int:cultivo_id>/muestreos/', muestreo_listar, name='muestreo_listar'),
    path('cultivos/<int:cultivo_id>/muestreos/grafica/', grafica_muestreo, name='grafica_muestro'),
    path('cultivos/<int:cultivo_id>/muestreos/registrar/', muestreo_registrar, name='muestreo_registrar'),
    path('cultivos/<int:cultivo_id>/muestreos/<int:muestreo_id>/editar/', muestreo_editar, name='muestreo_editar'),
    path('cultivos/<int:cultivo_id>/muestreos/<int:muestreo_id>/', muestreo_detalle, name='muestreo_detalle'),
    path('cultivos/<int:cultivo_id>/mortalidad/', mortalidad_registrar, name='mortalidad_registrar'),
    # ----alimentacion
    path('cultivos/<int:cultivo_id>/alimentacion/', alimentacion_listar, name='alimentacion_listar'),
    path('cultivos/<int:cultivo_id>/alimentacion/registrar/', alimentacion_registrar, name='alimentacion_registrar'),
    path('cultivos/<int:cultivo_id>/alimentacion/<int:alimentacion_id>/editar/', alimentacion_editar,
         name='alimentacion_editar'),
    # ----calidad agua
    path('estanques/<int:estanque_id>/calidad_agua/', calidad_agua_listar, name='calidad_agua_listar'),
    path('estanques/<int:estanque_id>/calidad_agua/registrar/', calidad_agua_registrar,
         name='calidad_agua_registrar'),
    path('estanques/<int:estanque_id>/calidad_agua/<int:calidad_agua_id>/', calidad_agua_detalle,
         name='calidad_agua_detalle'),
    path('estanques/<int:estanque_id>/calidad_agua/<int:calidad_agua_id>/editar/', calidad_agua_editar,
         name='calidad_agua_editar'),
    path('estanques/<int:estanque_id>/calidad_agua/graficas_agua/', graficas_agua, name='graficas_agua'),
    path('estanques/calidad_agua_rangos/', calidad_agua_rangos_create, name='calidad_agua_rangos_create'),
]

registro/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('piscicola/', la_piscicola, name='la_piscicola'),
    path('cosechas/', cosecha_list, name='cosecha_list'),
    # --------------------------------------------------------------------------------------
    path('estanques/', estanque_list, name='estanque_list'),
    path('estanques/crear/', estanque_crear, name='estanque_crear'),
    path('estanques/<int:estanque_id>/',estanque_detalle, name='estanque_detalle'),
    path('estanques/<int:estanque_id>/editar/', estanque_editar, name='estanque_editar'),
    # --------------------------------------------------------------------------------------
    path('cultivos/', cultivo_list, name='cultivo_list'),
    path('cultivos/crear/',cultivo_crear, name='cultivo_crear'),
    path('cultivos/<int:cultivo_id>/',cultivo_detalle, name='cultivo_detalle'),
    path('cultivos/<int:cultivo_id>/editar/', cultivo_editar, name='cultivo_editar'),
    path('cultivos/<int:cultivo_id>/cosechar/', cultivo_cosechar, name='cultivo_cosechar'),
]

users/urls.py
from django.urls import path
from users import views as user_views
from django.contrib.auth.decorators import login_required

# Python Django Tutorial: Full-Featured Web App Part 7 - Login and Logout System
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('registrar/', user_views.registrar, name='registrar'),
    path('ingresar/', auth_views.LoginView.as_view(template_name='users/ingresar.html'), name='ingresar'),
    path('salir/', auth_views.LogoutView.as_view(template_name='users/salir.html'), name='salir'),
    path('perfil/', user_views.perfil, name='perfil'),
]

registro/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from django.core.validators import MinValueValidator
from django.urls import reverse
from django.db.models.signals import pre_save
from django.dispatch import receiver


class Finca(models.Model):
    razon_social = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True)

    def __str__(self):
        return self.razon_social

    def save(self, *args, **kwargs):
        self.slug = slugify(self.razon_social)
        super(Finca, self).save(*args, **kwargs)


# ----------------------------------------------------------------------------------------------------------------------
class Estanque(models.Model):
    nombre = models.CharField(max_length=100)
    tipo = models.CharField(max_length=100)
    nivel_agua_mts = models.DecimalField(max_digits=5, decimal_places=2,
                                         validators=[MinValueValidator(0)])
    mts_2 = models.DecimalField(max_digits=5, decimal_places=2, validators=[MinValueValidator(0)])
    detalle = models.TextField(blank=True, null=True)
    # --------------------------------------------------------------------------------------
    finca = models.ForeignKey(Finca, on_delete=models.CASCADE, blank=True)
    responsable = models.CharField(max_length=100)
    fecha_registro = models.DateTimeField(default=timezone.now)
    fecha_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

    # class Meta:
    #     unique_together = (
    #        ('finca', 'nombre'),
    #     )


# ----------------------------------------------------------------------------------------------------------------------
class Cultivo(models.Model):
    CHOICES = (('siembra', 'siembra'), ('levante', 'levante'), ('engorde', 'engorde'))
    nombre = models.CharField(max_length=100)
    estanque = models.ForeignKey(Estanque, on_delete=models.SET_NULL, null=True)
    especie = models.CharField(max_length=50, default='tilapia')
    cantidad = models.PositiveIntegerField(validators=[MinValueValidator(0)])
    tamaño_pez_cm = models.DecimalField(max_digits=5, decimal_places=1, validators=[MinValueValidator(0)])
    peso_pez_gr = models.DecimalField(max_digits=5, decimal_places=1, validators=[MinValueValidator(0)])
    densidad_inicial = models.PositiveSmallIntegerField(blank=True, null=True)
    etapa = models.CharField(max_length=7, choices=CHOICES, default='siembra')
    detalle = models.TextField(blank=True, null=True)
    # ----
    finca = models.ForeignKey(Finca, on_delete=models.CASCADE)
    responsable = models.CharField(max_length=100)
    cosechado = models.BooleanField(default=False)
    fecha_registro = models.DateTimeField(default=timezone.now)
    fecha_cosecha = models.DateTimeField(blank=True, null=True)
    fecha_update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('cultivo_detalle', kwargs={'cultivo_id': self.id})  # f"/products/{self.id}/"

    def total_peces(self):
        total_muertes = 0
        for mortalidad in self.mortalidad_set.all():
            total_muertes += mortalidad.peces_muertos
        return self.cantidad - total_muertes

    def alimento_promedio(self):
        """alimento promedio diario"""
        alimento_total = 0
        alimentacion = self.alimentacion_set.all()
        numero_elementos = alimentacion.count()
        if numero_elementos == 0:
            return 0
        else:
            for alimentacion in alimentacion:
                alimento_total += alimentacion.total()
            promedio = alimento_total / numero_elementos
            return promedio


# @receiver(pre_save, sender=Cultivo)
# def calculos_muestreo(sender, instance, *args, **kwargs):

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


# class UserUpdateForm(forms.ModelForm):
#     email = forms.EmailField()
#
#     class Meta:
#         model = User
#         fields = ['username', 'email']


# class ProfileUpdateForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ['image', 'trabaja_en']

registro/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import EstanqueCreateForm, EstanqueEditForm, CultivoCreateForm, CultivoEditForm
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.views.generic import ListView,CreateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from datetime import datetime

@login_required
def la_piscicola(request):  # página inicial logeado
    la_piscicola_obj = request.user.profile.trabaja_en
    print(request.user.profile.trabaja_en)
    if la_piscicola_obj is not None:
        if 'la_piscicola' not in request.session:
            request.session['la_piscicola'] = la_piscicola_obj.id
    # raise Http404("Este usuario no tiene un finca asignada")
    else:
        messages.error(request, 'el usuario no esta asignado a ninguna finca')
    context = {
        'la_piscicola': la_piscicola_obj
    }
    return render(request, 'registro/la_piscicola.html', context)

# ----estanque views----------------------------------------------------------------------------------------------------
@login_required
def estanque_list(request):
    finca = None
    lista = None
    if request.user.is_authenticated:
        # print(request.session['la_piscicola'])
        finca = request.user.profile.trabaja_en
        #                               finca__id=request.session['la_piscicola']
        lista = Estanque.objects.filter(finca=finca).order_by('-fecha_registro')
        mensaje = 'consulta exitosa'
        if finca is None:
            mensaje = 'no perteneces a ninguna finca consulta con el administrador'
    else:
        mensaje='error: no ha iniciado sesión'
    context = {
        'la_piscicola': finca,
        'titulo': 'Mis estanques',
        'estanques': lista,
        'mensaje': mensaje
    }
    return render(request, 'registro/estanque_list.html', context)


@login_required
def estanque_crear(request):
    if request.method == 'POST':
        form = EstanqueCreateForm(request.POST or None)
        if form.is_valid():
            estanque = form.save(commit=False)
            estanque.finca = request.user.profile.trabaja_en
            estanque.responsable = request.user
            estanque.save()
            return redirect('estanque_list')
    else:
        form = EstanqueCreateForm()
    context={
        'form': form,
        'titulo': ' Nuevo estanque'
    }
    return render(request, 'registro/estanque_crear.html', context)


@login_required
def estanque_detalle(request, estanque_id):
    estanque = get_object_or_404(Estanque, pk=estanque_id)
    return render(request,'registro/estanque_detalle.html', {'estanque': estanque})


@login_required
def estanque_editar(request, estanque_id):
    objeto = get_object_or_404(Estanque, pk=estanque_id)
    form = EstanqueEditForm(request.POST or None, instance=objeto, estanque_id=estanque_id)
    if form.is_valid():
        form.save()
        return redirect('estanque_detalle', estanque_id)
    context = {
        'form': form,
        'titulo': 'Editar estanque'
    }
    return render(request, 'registro/estanque_crear.html', context)


# ----cultio views------------------------------------------------------------------------------------------------------
@login_required
def cultivo_list(request):
    finca = None
    lista = None
    if request.user.is_authenticated:
        finca = request.user.profile.trabaja_en
        lista = Cultivo.objects.filter(finca=finca, cosechado=False).order_by('-fecha_registro')
        mensaje = 'consulta exitosa'
        if finca is None:
            mensaje = 'tu cuenta no esta asociada a ninguna finca consulta con el administrador'
    else:
        mensaje='error: no ha iniciado sesión'

    context = {
        'la_piscicola': finca,
        'titulo': 'Mis cultivos',
        'cultivos': lista,
        'mensaje': mensaje
    }
    return render(request, 'registro/cultivo_list.html', context)


@login_required
def cultivo_crear(request):
    form = CultivoCreateForm()
    if request.method == 'POST':
        form = CultivoCreateForm(request.POST)
        if form.is_valid():
            cultivo = form.save(commit=False)
            cultivo.finca = request.user.profile.trabaja_en
            cultivo.responsable = request.user
            peso = form.cleaned_data['peso_pez_gr']
            if 40 < peso < 120:
                cultivo.etapa = "levante"
                cultivo.save()
            if peso >= 120:
                cultivo.etapa = "engorde"
                cultivo.save()
            else:
                cultivo.save()
            return redirect('cultivo_list')
    context = {
        'form': form,
        'titulo': 'Nuevo cultivo'
    }
    return render(request, 'registro/cultivo_crear.html', context)


@login_required
def cultivo_detalle(request, cultivo_id):
    try:
        cultivo = Cultivo.objects.get(pk=cultivo_id)
    except Cultivo.DoesNotExist:
        raise Http404("no existe ese cultivo")
    return render(request, 'registro/cultivo_detalle.html', {'cultivo': cultivo})


@login_required
def cultivo_editar(request, cultivo_id):
    objeto = get_object_or_404(Cultivo, pk=cultivo_id)
    form = CultivoEditForm(request.POST or None, instance=objeto, cultivo_id=cultivo_id)
    if request.method == 'POST':
        print(form.errors)
        if form.is_valid():
            print('es valido')
            cultivo = form.save(commit=False)
            peso = cultivo.peso_pez_gr
            if 40 < peso < 120:
                cultivo.etapa = "levante"
                cultivo.save()
            if peso >= 120:
                cultivo.etapa = "engorde"
                cultivo.save()
            else:
                cultivo.save()
            return redirect('cultivo_detalle', cultivo_id)
    context = {
        'form': form,
        'titulo': 'Editar cultivo'
    }
    return render(request, 'registro/cultivo_crear.html', context)


@login_required
def cosecha_list(request):
    finca = None
    lista = None
    if request.user.is_authenticated:
        finca = request.user.profile.trabaja_en
        lista = Cultivo.objects.filter(finca=finca, cosechado=True).order_by('-fecha_update')
        mensaje = 'consulta exitosa'
        if finca is None:
            mensaje = 'tu cuenta no esta asociada a ninguna finca consulta con el administrador'
    else:
        mensaje = 'error: no ha iniciado sesión'

    context = {
        'la_piscicola': finca,
        'titulo': 'Mis cosechas',
        'cosechas': lista,
        'mensaje': mensaje
    }
    return render(request, 'registro/cosecha_list.html', context)


def cultivo_cosechar(request, cultivo_id):
    cultivo = Cultivo.objects.get(pk=cultivo_id)
    if request.method == 'POST':
        cultivo.cosechado = True
        cultivo.fecha_cosecha = datetime.now()
        cultivo.save()
        return redirect('cosecha_list')
    context = {
        'cultivo': cultivo,
    }
    return render(request, 'registro/cultivo_cosechar.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm # , UserUpdateForm, ProfileUpdateForm
from registro.models import Finca


# Python Django Tutorial: Full-Featured Web App Part 6 - User Registration
def registrar(request):
    if request.method == 'POST':
        # form = UserCreationForm(request.POST or None)
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'registro de {} exitoso!'.format(username))
            return redirect('inicio')
    else:
        # form = UserCreationForm()
        form = UserRegisterForm
    return render(request, 'users/registro.html',{'form': form})

# messages.debug
# messages.info
# messages.success
# messages.warning
# messages.error

@login_required
def perfil(request):
    try:
        la_pisciola = request.user.profile.trabaja_en
    except:
        la_pisciola = None
    context={
        'la_piscicola': la_pisciola
    }
    return render(request, 'users/perfil.html', context)

    # if request.method == 'POST':
    #     u_form = UserUpdateForm(request.POST, instance=request.user)
    #     p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
    #     if u_form.is_valid() and p_form.is_valid():
    #         u_form.save()
    #         p_form.save()
    #         messages.success(request, 'tu perfil ha actualizado')
    #         return redirect('perfil')
    # else:
    #     u_form = UserUpdateForm(instance=request.user)
    #     p_form = ProfileUpdateForm(instance=request.user.profile)
    # try:
    #     finca = Finca.objects.get(usuarios=request.user)
    # except Finca.DoesNotExist:
    #     finca = None
    #
    # context={
    #      'la_piscicola': finca,
    #      'u_form': u_form,
    #      'p_form': p_form
    # }
    #
    # print(request.user.groups.all)
    # return render(request, 'users/perfil.html', context)

templates/users/ingresar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Ingresar
{% endblock %}

{% block main_title %}
    Ingresar
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m6 offset-m3 valign">
            <div class="card">
                <div class="card-content ">
                    <span class="card-title"></span>
                    <form class="crecer" id="ingresar" method="POST">
                        {% csrf_token %}
                        <!-- en ves de usar .as_p puedo usar |crispy -->
                        {{ form.as_p }}
                    </form>
                    <div class="center">
                        <button class="full_ancho btn waves-light waves-effect light-blue lighten-1" type="submit" form="ingresar">
                            Ingresar
                        </button>
                    </div>
                </div>
                {#                <div class="card-action">#}
                {#                    #}
                {#                </div>#}
            </div>
        </div>
    </div>
{% endblock %}

templates/users/perfil.html
{% extends 'base.html' %}
{#{% load crispy_forms_tags %}#}

{% block title %}
    Mi perfil
{% endblock %}

{% block main_title %}
    Mi perfil
{% endblock %}

{% block micontenido %}
    {% if la_piscicola %}
        <div class="row valign-wrapper">
        <div class="col m6 s12">
            <h4 class="left">finca: {{ la_piscicola.razon_social }}</h4>
        </div>
        <div class="col m6 s12">
            <a href="{% url 'control:calidad_agua_rangos_create' %}"
               class="btn btn-large btn-flat waves-effect waves-light right nowrap">
            rangos calidad agua
            </a>
        </div>
        </div>

    {% else %}
        No has configurado una finca, comunícate con el administrador
    {% endif %}
    <div class="section" >
        <i class="left"><img class="responsive-img circle small" src="{{ user.profile.image.url }}"
                             height="80" width="80" alt=""></i>
        <h5 class="valign-wrapper">username: {{ user.username }}</h5>
    </div>

        <p>nombre: {{ user.firstname }}</p>
        <p>apellidos: {{ user.lastname}}</p>
{#        <p>cargo: {{ user.groups.all.0 }}</p>#}
        <p> cargo: {% if user.profile.rol == 1 %} Administrador {% else %} Trabajador {% endif %}</p>
        <p>email: </p>{{ user.email }}

{#        {% ifequal user.groups.all.0.name "Jefe" %}#}
{#        {% else %}#}
        <p>Ultima conexión: {{ user.last_login }}</p>
{#        {% endifequal %}#}
    <br>
{#    <div class="row">#}
{#        <div class="col s12 m6 l6">#}
{#            <div class="card">#}
{#                <div class="card-content">#}
{#                    <span class="card-title">Información</span>#}
{#                    <form method="post" enctype="multipart/form-data">#}
{#                        {% csrf_token %}#}
{#                        {{ u_form.as_p }}#}
{#                        <div class="ningun">#}
{#                            {{ p_form.as_p }}#}
{#                        </div>#}
{##}
{#                        <button class="btn light-blue" type="submit">actualizar</button>#}
{#                    </form>#}
{#                </div>#}
{##}
{#            </div>#}
{#        </div>#}
{#    </div>#}

{% endblock %}

templates/users/registro.html
{% extends 'base.html' %}

<!-- colores-->
blue-grey darken-4 white-text

{% load crispy_forms_tags %}

{% block main_title %}
    Regitro
{% endblock %}

{% block micontenido %}
    <div class="row">
        <div class="col s12 m8">
            <div class="card ">
                <div class="card-content ">
                    <span class="card-title">Registro | Nuevo usuario</span>
                    <form class="crecer" method="POST">
                        {% csrf_token %}
                        <!-- en ves de usar .as_p usare |crispy un tag de crispy-->

                        {{ form.as_p }}
                        <br>
                        <button class="btn waves-effect waves-light" type="submit" name="action">
                            Registrarse
                            <i class="material-icons right">send</i>
                        </button>
                    </form>
                </div>
                {#        <div class="card-action">#}
                {##}
                {#        </div>#}
            </div>
        </div>
    </div>

    <button class="btn modal-trigger small right" data-target="modal1">Modal</button>

    <!--clases modal: botton-sheet modal-fixed-footer-->
    <div class="modal" id="modal1">
        <div class="modal-content">
            <p>modal alert de materialize, solo para probrar el botón</p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn modal-close waves-effect waves-deafult">cerrar</a>
        </div>
    </div>

    <script type="text/javascript">
        /*(document).ready(function(){
            $('#modal1').leanModal({

                dismissible: true, // Modal can be dismissed by clicking outside of the modal
                opacity: .5, // Opacity of modal background
                in_duration: 300, // Transition in duration
                out_duration: 200, // Transition out duration
                //ready: function() { alert('Ready'); }, // Callback for Modal open
                complete: function() { alert('Closed'); } // Callback for Modal close

                ready:function () { close();}
            });
        });
        function close() {
            setTimeout(function () {
                $('#modal1').closeModal()},4000)
        };*/
    </script>
{% endblock %}

templates/users/salir.html
{% extends 'base.html' %}


{% block title %}
    Salir
{% endblock %}

{% block main_title %}
    <span>Has cerrado sessión</span>
{% endblock %}

{% block micontenido %}
<i class="medium material-icons">mood</i><i class="medium material-icons">free_breakfast</i>
{% endblock %}